# samsung_tv_remote (AA59-00741A)
# path: /storage/.config/rc_keymaps/samsung_tv_remote.toml
# NOTE: keys for scripts/special functions have no mapping in kodi (KEY_F1, ...)
[[protocols]]
name = "samsung_tv_remote"
protocol = "nec"
variant = "necx"

[protocols.scancodes]
# KEY_F6: call rest-api: turn tv on
0x70702 = "KEY_F6" # power
0x70768 = "KEY_OK" # ok
0x70765 = "KEY_LEFT" # left
0x70762 = "KEY_RIGHT" # right
0x70760 = "KEY_UP" # up
0x70761 = "KEY_DOWN" # down
0x70758 = "KEY_EXIT" # return
0x7072d = "KEY_MENU" # exit
0x7076c = "KEY_POWER" # red
0x70714 = "KEY_F1" # green (DISPLAY???) FullScreen Toggle
0x70715 = "KEY_VOLUMEDOWN" # yellow
0x70716 = "KEY_VOLUMEUP" # blue
0x70746 = "KEY_STOP" # stop
0x70747 = "KEY_PLAY" # play
0x7074a = "KEY_PAUSE" # pause
0x70748 = "KEY_FORWARD" # forward
0x70745 = "KEY_REWIND" # rewind
0x70704 = "KEY_1" # 1
0x70705 = "KEY_2" # 2
0x70706 = "KEY_3" # 3
0x70708 = "KEY_4" # 4
0x70709 = "KEY_5" # 5
0x7070a = "KEY_6" # 6
0x7070c = "KEY_7" # 7
0x7070d = "KEY_8" # 8
0x7070e = "KEY_9" # 9
0x70711 = "KEY_0" # 0
# KEY_F5: disable eventlircd service and re-enable after 60 sec. to configure TV without trigger kodi actions
0x7071a = "KEY_F5" # menu
#0x7071f = "" # info
#0x7072c = "" # ttx/mix
#0x70713 = "" # pre-ch
#0x7074f = "" # guide
0x7076b = "KEY_TV" # ch list
#0x70725 = "" # ad/subst
